# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x63ontroller.proto\"4\n\x10InferenceRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"E\n\x11InferenceResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x1e\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0f.PotentialError\";\n\x12ModelManageRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\x05\"\"\n\x0ePotentialError\x12\x10\n\x08\x65rrorMsg\x18\x01 \x01(\t2\xa0\x01\n\nController\x12\x30\n\x05Infer\x12\x11.InferenceRequest\x1a\x12.InferenceResponse\"\x00\x12.\n\x04Load\x12\x13.ModelManageRequest\x1a\x0f.PotentialError\"\x00\x12\x30\n\x06Unload\x12\x13.ModelManageRequest\x1a\x0f.PotentialError\"\x00\x62\x06proto3'
)




_INFERENCEREQUEST = _descriptor.Descriptor(
  name='InferenceRequest',
  full_name='InferenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='InferenceRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='InferenceRequest.model_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=72,
)


_INFERENCERESPONSE = _descriptor.Descriptor(
  name='InferenceResponse',
  full_name='InferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='InferenceResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='InferenceResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=143,
)


_MODELMANAGEREQUEST = _descriptor.Descriptor(
  name='ModelManageRequest',
  full_name='ModelManageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='ModelManageRequest.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='ModelManageRequest.worker_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=204,
)


_POTENTIALERROR = _descriptor.Descriptor(
  name='PotentialError',
  full_name='PotentialError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorMsg', full_name='PotentialError.errorMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=240,
)

_INFERENCERESPONSE.fields_by_name['error'].message_type = _POTENTIALERROR
DESCRIPTOR.message_types_by_name['InferenceRequest'] = _INFERENCEREQUEST
DESCRIPTOR.message_types_by_name['InferenceResponse'] = _INFERENCERESPONSE
DESCRIPTOR.message_types_by_name['ModelManageRequest'] = _MODELMANAGEREQUEST
DESCRIPTOR.message_types_by_name['PotentialError'] = _POTENTIALERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferenceRequest = _reflection.GeneratedProtocolMessageType('InferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREQUEST,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:InferenceRequest)
  })
_sym_db.RegisterMessage(InferenceRequest)

InferenceResponse = _reflection.GeneratedProtocolMessageType('InferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERESPONSE,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:InferenceResponse)
  })
_sym_db.RegisterMessage(InferenceResponse)

ModelManageRequest = _reflection.GeneratedProtocolMessageType('ModelManageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELMANAGEREQUEST,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:ModelManageRequest)
  })
_sym_db.RegisterMessage(ModelManageRequest)

PotentialError = _reflection.GeneratedProtocolMessageType('PotentialError', (_message.Message,), {
  'DESCRIPTOR' : _POTENTIALERROR,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:PotentialError)
  })
_sym_db.RegisterMessage(PotentialError)



_CONTROLLER = _descriptor.ServiceDescriptor(
  name='Controller',
  full_name='Controller',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=243,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='Infer',
    full_name='Controller.Infer',
    index=0,
    containing_service=None,
    input_type=_INFERENCEREQUEST,
    output_type=_INFERENCERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='Controller.Load',
    index=1,
    containing_service=None,
    input_type=_MODELMANAGEREQUEST,
    output_type=_POTENTIALERROR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Unload',
    full_name='Controller.Unload',
    index=2,
    containing_service=None,
    input_type=_MODELMANAGEREQUEST,
    output_type=_POTENTIALERROR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLER)

DESCRIPTOR.services_by_name['Controller'] = _CONTROLLER

# @@protoc_insertion_point(module_scope)
