# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cworker.proto\"$\n\x10InferenceRequest\x12\x10\n\x08json_obj\x18\x01 \x01(\t\"\xd2\x01\n\x11InferenceResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12/\n\x0cinfer_status\x18\x02 \x01(\x0e\x32\x19.InferenceResponse.Status\x12\x11\n\terror_msg\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x10\n\x08json_obj\x18\x05 \x01(\t\"A\n\x06Status\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\x0c\n\x08UNLOADED\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\"(\n\x12ModelManageRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"\xa6\x01\n\x13ModelManageResponse\x12\x31\n\x0cmodel_status\x18\x01 \x01(\x0e\x32\x1b.ModelManageResponse.Status\x12\x11\n\terror_msg\x18\x02 \x01(\t\"I\n\x06Status\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\x14\n\x10NOT_ENOUGH_SPACE\x10\x01\x12\x0c\n\x08UNLOADED\x10\x02\x12\n\n\x06LOADED\x10\x03\"\x10\n\x0eMetricsRequest\"\'\n\x0fMetricsResponse\x12\x14\n\x0cmetrics_json\x18\x01 \x01(\t2\xd9\x01\n\x06Worker\x12\x30\n\x05Infer\x12\x11.InferenceRequest\x1a\x12.InferenceResponse\"\x00\x12\x33\n\x04Load\x12\x13.ModelManageRequest\x1a\x14.ModelManageResponse\"\x00\x12\x35\n\x06Unload\x12\x13.ModelManageRequest\x1a\x14.ModelManageResponse\"\x00\x12\x31\n\nGetMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponse\"\x00\x62\x06proto3'
)



_INFERENCERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='InferenceResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNAVAILABLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNLOADED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=200,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_INFERENCERESPONSE_STATUS)

_MODELMANAGERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ModelManageResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNAVAILABLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_ENOUGH_SPACE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNLOADED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOADED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=403,
  serialized_end=476,
)
_sym_db.RegisterEnumDescriptor(_MODELMANAGERESPONSE_STATUS)


_INFERENCEREQUEST = _descriptor.Descriptor(
  name='InferenceRequest',
  full_name='InferenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_obj', full_name='InferenceRequest.json_obj', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=52,
)


_INFERENCERESPONSE = _descriptor.Descriptor(
  name='InferenceResponse',
  full_name='InferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='InferenceResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='infer_status', full_name='InferenceResponse.infer_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='InferenceResponse.error_msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='InferenceResponse.request_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='json_obj', full_name='InferenceResponse.json_obj', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INFERENCERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=265,
)


_MODELMANAGEREQUEST = _descriptor.Descriptor(
  name='ModelManageRequest',
  full_name='ModelManageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='ModelManageRequest.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=307,
)


_MODELMANAGERESPONSE = _descriptor.Descriptor(
  name='ModelManageResponse',
  full_name='ModelManageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_status', full_name='ModelManageResponse.model_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='ModelManageResponse.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELMANAGERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=476,
)


_METRICSREQUEST = _descriptor.Descriptor(
  name='MetricsRequest',
  full_name='MetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=494,
)


_METRICSRESPONSE = _descriptor.Descriptor(
  name='MetricsResponse',
  full_name='MetricsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics_json', full_name='MetricsResponse.metrics_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=535,
)

_INFERENCERESPONSE.fields_by_name['infer_status'].enum_type = _INFERENCERESPONSE_STATUS
_INFERENCERESPONSE_STATUS.containing_type = _INFERENCERESPONSE
_MODELMANAGERESPONSE.fields_by_name['model_status'].enum_type = _MODELMANAGERESPONSE_STATUS
_MODELMANAGERESPONSE_STATUS.containing_type = _MODELMANAGERESPONSE
DESCRIPTOR.message_types_by_name['InferenceRequest'] = _INFERENCEREQUEST
DESCRIPTOR.message_types_by_name['InferenceResponse'] = _INFERENCERESPONSE
DESCRIPTOR.message_types_by_name['ModelManageRequest'] = _MODELMANAGEREQUEST
DESCRIPTOR.message_types_by_name['ModelManageResponse'] = _MODELMANAGERESPONSE
DESCRIPTOR.message_types_by_name['MetricsRequest'] = _METRICSREQUEST
DESCRIPTOR.message_types_by_name['MetricsResponse'] = _METRICSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferenceRequest = _reflection.GeneratedProtocolMessageType('InferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:InferenceRequest)
  })
_sym_db.RegisterMessage(InferenceRequest)

InferenceResponse = _reflection.GeneratedProtocolMessageType('InferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:InferenceResponse)
  })
_sym_db.RegisterMessage(InferenceResponse)

ModelManageRequest = _reflection.GeneratedProtocolMessageType('ModelManageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELMANAGEREQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:ModelManageRequest)
  })
_sym_db.RegisterMessage(ModelManageRequest)

ModelManageResponse = _reflection.GeneratedProtocolMessageType('ModelManageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELMANAGERESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:ModelManageResponse)
  })
_sym_db.RegisterMessage(ModelManageResponse)

MetricsRequest = _reflection.GeneratedProtocolMessageType('MetricsRequest', (_message.Message,), {
  'DESCRIPTOR' : _METRICSREQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:MetricsRequest)
  })
_sym_db.RegisterMessage(MetricsRequest)

MetricsResponse = _reflection.GeneratedProtocolMessageType('MetricsResponse', (_message.Message,), {
  'DESCRIPTOR' : _METRICSRESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:MetricsResponse)
  })
_sym_db.RegisterMessage(MetricsResponse)



_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=538,
  serialized_end=755,
  methods=[
  _descriptor.MethodDescriptor(
    name='Infer',
    full_name='Worker.Infer',
    index=0,
    containing_service=None,
    input_type=_INFERENCEREQUEST,
    output_type=_INFERENCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='Worker.Load',
    index=1,
    containing_service=None,
    input_type=_MODELMANAGEREQUEST,
    output_type=_MODELMANAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Unload',
    full_name='Worker.Unload',
    index=2,
    containing_service=None,
    input_type=_MODELMANAGEREQUEST,
    output_type=_MODELMANAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMetrics',
    full_name='Worker.GetMetrics',
    index=3,
    containing_service=None,
    input_type=_METRICSREQUEST,
    output_type=_METRICSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
